### PR TITLE
Example: codeigniter

### PR DESCRIPTION
**Pull request by rolandihms**
Uploaded Codeigniter example

### CODE REVIEW

**Comment by f3l1x** [comment]
Hi could you please rebase it to latest master? Thanks.

**Comment by f3l1x** [comment]
Can you please rebase it?

**Comment by rolandihms** [comment]
Hey @f3l1x , just rebased, sorry about the delay here. Let me know if there is anything else you require... Maybe there is someone out there who needs to port his old codeigniter app to a serverless landscape...

**Comment by f3l1x** [comment]
Thank you

**Pull request merged**
